imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        gc_probability: 0
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
#    form:
#            resources: ['bootstrap_3_layout.html.twig']

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Siplo\UserBundle\Entity\SiploUser

#IF you change path of the uploding elemen of Vich uploader bundle, You also have to change the relevent base path
#in easy_admin

vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
            uploaded_video:
                uri_prefix:         /uploads/videos
                upload_destination: %kernel.root_dir%/../web/uploads/videos
                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true
            video_thumbnail:
                uri_prefix:         /uploads/video_thumbnails
                upload_destination: %kernel.root_dir%/../web/uploads/video_thumbnails
                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true

            country_background:
                uri_prefix:         /thumbs/country_backgrounds
                upload_destination: %kernel.root_dir%/../web/thumbs/country_backgrounds
                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true

            country_flag:
                uri_prefix:         /thumbs/country_flags
                upload_destination: %kernel.root_dir%/../web/thumbs/country_flags
                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true

            uploaded_photo:
                uri_prefix:         /uploads/photos
                upload_destination: %kernel.root_dir%/../web/uploads/photos
                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true

            category_background:
                uri_prefix:         /thumbs/category_backgrounds
                upload_destination: %kernel.root_dir%/../web/thumbs/category_backgrounds
                inject_on_load:     false
                delete_on_update:   true
                delete_on_remove:   true

            sub_category_background:
                            uri_prefix:         /thumbs/sub_category_backgrounds
                            upload_destination: %kernel.root_dir%/../web/thumbs/sub_category_backgrounds
                            inject_on_load:     false
                            delete_on_update:   true
                            delete_on_remove:   true

# you will get these parameters form https://code.google.com/apis/console/"
happy_r_google_api:
  application_name: TourismOnNet
  oauth2_client_id: 758651250413-kcs13o7hre1bomb2rfs4mgnengknklae.apps.googleusercontent.com
  oauth2_client_secret: bKVhmAqV5fin2NBrgXblG1Eo
  oauth2_redirect_uri: https://accounts.google.com/o/oauth2/auth
  developer_key: "bhh"
  site_name: mysite.com

easy_admin:
    design:
            # this backend uses turquoise as its main color
            brand_color: '#1ABC9C'
            color_scheme: 'light'
    entities:
        User:
                class: Siplo\UserBundle\Entity\SiploUser
                label: 'Users'
                list:
                    fields:
                        - id
                        - username
                        - email
                        - locked
                    actions: ['-edit']
                form:
                    fields:
                        - username
                        - email
                        - plainPassword
                        - roles
                        - enabled
        Category:
                        class: Siplo\MediaBundle\Entity\Category
                        label: 'Categories'
                        list:
                            fields:
                                - { property: 'id'}
                                - { property: 'title'}
                                - { property: 'backgroundFileName', label: 'Background Image',type: 'image', base_path: '/thumbs/category_backgrounds/' }

                        form:
                            fields:
                                - title
#                                - code
                                - { property: 'backgroundImage', type: 'file', label: 'Upload Background', help: 'Select file to upload / change logo'}

        Country:
                class: Siplo\MediaBundle\Entity\Country
                label: 'Countries'
                list:
                    fields:
                        - { property: 'id'}
                        - { property: 'name'}
                        - { property: 'backgroundImageFileName', label: 'Background Image', type: 'image', base_path: '/thumbs/country_backgrounds/' }

                form:
                    fields:
                        - name
#                        - code
                        - { property: 'backgroundImage', type: 'file', label: 'Upload Background', help: 'Select file to upload / change logo'}
                        - { property: 'flag', type: 'file', label: 'Upload Flag', help: 'Select file to upload / change logo'}
                        - { property: 'categories'}


        SubCategory:
                class: Siplo\MediaBundle\Entity\SubCategory
                label: 'Sub Categories'
                list:
                    fields:
                        - { property: 'id'}
                        - { property: 'title'}
                        - { property: 'backgroundFileName', label: 'Background Image', type: 'image', base_path: '/thumbs/sub_category_backgrounds/' }

                form:
                    fields:
                        - title
#                        - code
                        - { property: 'backgroundImage', type: 'file', label: 'Upload Background', help: 'Select file to upload / change logo'}
                        - { property: 'country'}
                        - { property: 'category'}
                        - { property: 'description'}

        FurtherDetails:
                class: Siplo\MediaBundle\Entity\FurtherDetails
                label: 'Further Details'
                list:
                    fields:
                        - { property: 'id'}
                form:
                    fields:
                        - { property: 'subCategory'}
                        - body
        Photo:
                class: Siplo\MediaBundle\Entity\Photo
                label: 'Photos'
                list:
                    fields:
                        - { property: 'id'}
                        - { property: 'title'}
                        - { property: 'photoFileName', label: 'Preview', type: 'image', base_path: '/uploads/photos/' }
                        - { property: 'country'}
                        - { property: 'category'}
                        - { property: 'subCategory'}
                        - { property: 'authorised'}
                    actions: ['preview']
                form:
                    fields:
                        - { property: 'title'}
                        - { property: 'authorised'}
                        - { property: 'country'}
                        - { property: 'category'}
                        - { property: 'subCategory'}
                        - { property: 'rating'}
                        - { property: 'photo', type: 'file', label: 'Change Photo', help: 'Select file to upload / change photo'}
        Video:
                class: Siplo\MediaBundle\Entity\Video
                label: 'Videos'
                list:
                    fields:
                        - { property: 'id'}
                        - { property: 'videoName'}
                        - { property: 'thumbName', label: 'Preview', type: 'image', base_path: '/uploads/video_thumbnails/' }
                        - { property: 'country'}
                        - { property: 'category'}
                        - { property: 'subCategory'}
                        - { property: 'authorised'}
                    actions: ['play']
                form:
                    fields:
                        - { property: 'VideoTitle'}
                        - { property: 'authorised'}
                        - { property: 'country'}
                        - { property: 'category'}
                        - { property: 'subCategory'}
                        - { property: 'rating'}
                        - {property: 'youtubeLink'}
                        - { property: 'videoFile', type: 'file', label: 'Change Video', help: 'Select file to upload / change video'}
                        - { property: 'thumbnail', type: 'file', label: 'Change Thumbnail', help: 'Select file to upload / change thumbnail'}

    site_name: 'Tourism On Net'

#Liip imagine
liip_imagine:
    resolvers:
            default:
                web_path:
                    web_root: %kernel.root_dir%/../web
                    cache_prefix: media/cache

    loaders:
        default:
            filesystem:
                data_root:   %kernel.root_dir%/../web/

    driver:               gd
    cache:                default
    data_loader:          default
    default_image:        null
    controller:
        filter_action:         liip_imagine.controller:filterAction
        filter_runtime_action: liip_imagine.controller:filterRuntimeAction

    filter_sets:
        cache: ~
        my_thumb:
            quality: 75
            filters:
                thumbnail: { size: [60, 35], mode: outbound }
        home_country_background:
                    quality: 75
                    filters:
                        thumbnail: { size: [160, 120], mode: outbound }
        home_country_flag:
                    quality: 75
                    filters:
                        thumbnail: { size: [60, 30], mode: outbound }
        home_sidebar_country_flag:
                    quality: 75
                    filters:
                        thumbnail: { size: [30, 15], mode: outbound }
        carousel_image:
                    quality: 75
                    filters:
                        thumbnail: { size: [640, 360], mode: outbound }